/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LinksRouteImport } from './routes/links'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicNetlifyCallbackRouteImport } from './routes/api/public/netlify.callback'
import { Route as ApiPublicNetlifyDeployRouteImport } from './routes/api/public/netlify.deploy'
import { Route as ApiPublicNetlifyStartRouteImport } from './routes/api/public/netlify.start'
import { Route as ApiPublicVercelDeployRouteImport } from './routes/api/public/vercel.deploy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNetlifyCallbackRoute =
  ApiPublicNetlifyCallbackRouteImport.update({
    id: '/api/public/netlify/callback',
    path: '/api/public/netlify/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNetlifyDeployRoute = ApiPublicNetlifyDeployRouteImport.update({
  id: '/api/public/netlify/deploy',
  path: '/api/public/netlify/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNetlifyStartRoute = ApiPublicNetlifyStartRouteImport.update({
  id: '/api/public/netlify/start',
  path: '/api/public/netlify/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVercelDeployRoute = ApiPublicVercelDeployRouteImport.update({
  id: '/api/public/vercel/deploy',
  path: '/api/public/vercel/deploy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/builder': typeof BuilderRoute
  '/gallery': typeof GalleryRoute
  '/links': typeof LinksRoute
  '/mcp': typeof McpRoute
  '/projects': typeof ProjectsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/p/$id': typeof PIdRoute
  '/u/$username': typeof UUsernameRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/netlify/callback': typeof ApiPublicNetlifyCallbackRoute
  '/api/public/netlify/deploy': typeof ApiPublicNetlifyDeployRoute
  '/api/public/netlify/start': typeof ApiPublicNetlifyStartRoute
  '/api/public/vercel/deploy': typeof ApiPublicVercelDeployRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/builder': typeof BuilderRoute
  '/gallery': typeof GalleryRoute
  '/links': typeof LinksRoute
  '/mcp': typeof McpRoute
  '/projects': typeof ProjectsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/p/$id': typeof PIdRoute
  '/u/$username': typeof UUsernameRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/netlify/callback': typeof ApiPublicNetlifyCallbackRoute
  '/api/public/netlify/deploy': typeof ApiPublicNetlifyDeployRoute
  '/api/public/netlify/start': typeof ApiPublicNetlifyStartRoute
  '/api/public/vercel/deploy': typeof ApiPublicVercelDeployRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/builder': typeof BuilderRoute
  '/gallery': typeof GalleryRoute
  '/links': typeof LinksRoute
  '/mcp': typeof McpRoute
  '/projects': typeof ProjectsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/p/$id': typeof PIdRoute
  '/u/$username': typeof UUsernameRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/netlify/callback': typeof ApiPublicNetlifyCallbackRoute
  '/api/public/netlify/deploy': typeof ApiPublicNetlifyDeployRoute
  '/api/public/netlify/start': typeof ApiPublicNetlifyStartRoute
  '/api/public/vercel/deploy': typeof ApiPublicVercelDeployRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/builder'
    | '/gallery'
    | '/links'
    | '/mcp'
    | '/projects'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/p/$id'
    | '/u/$username'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/netlify/callback'
    | '/api/public/netlify/deploy'
    | '/api/public/netlify/start'
    | '/api/public/vercel/deploy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/builder'
    | '/gallery'
    | '/links'
    | '/mcp'
    | '/projects'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/p/$id'
    | '/u/$username'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/netlify/callback'
    | '/api/public/netlify/deploy'
    | '/api/public/netlify/start'
    | '/api/public/vercel/deploy'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/builder'
    | '/gallery'
    | '/links'
    | '/mcp'
    | '/projects'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/p/$id'
    | '/u/$username'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/netlify/callback'
    | '/api/public/netlify/deploy'
    | '/api/public/netlify/start'
    | '/api/public/vercel/deploy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  BuilderRoute: typeof BuilderRoute
  GalleryRoute: typeof GalleryRoute
  LinksRoute: typeof LinksRoute
  McpRoute: typeof McpRoute
  ProjectsRoute: typeof ProjectsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  PIdRoute: typeof PIdRoute
  UUsernameRoute: typeof UUsernameRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicNetlifyCallbackRoute: typeof ApiPublicNetlifyCallbackRoute
  ApiPublicNetlifyDeployRoute: typeof ApiPublicNetlifyDeployRoute
  ApiPublicNetlifyStartRoute: typeof ApiPublicNetlifyStartRoute
  ApiPublicVercelDeployRoute: typeof ApiPublicVercelDeployRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/netlify/callback': {
      id: '/api/public/netlify/callback'
      path: '/api/public/netlify/callback'
      fullPath: '/api/public/netlify/callback'
      preLoaderRoute: typeof ApiPublicNetlifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/netlify/deploy': {
      id: '/api/public/netlify/deploy'
      path: '/api/public/netlify/deploy'
      fullPath: '/api/public/netlify/deploy'
      preLoaderRoute: typeof ApiPublicNetlifyDeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/netlify/start': {
      id: '/api/public/netlify/start'
      path: '/api/public/netlify/start'
      fullPath: '/api/public/netlify/start'
      preLoaderRoute: typeof ApiPublicNetlifyStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vercel/deploy': {
      id: '/api/public/vercel/deploy'
      path: '/api/public/vercel/deploy'
      fullPath: '/api/public/vercel/deploy'
      preLoaderRoute: typeof ApiPublicVercelDeployRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  BuilderRoute: BuilderRoute,
  GalleryRoute: GalleryRoute,
  LinksRoute: LinksRoute,
  McpRoute: McpRoute,
  ProjectsRoute: ProjectsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  PIdRoute: PIdRoute,
  UUsernameRoute: UUsernameRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicNetlifyCallbackRoute: ApiPublicNetlifyCallbackRoute,
  ApiPublicNetlifyDeployRoute: ApiPublicNetlifyDeployRoute,
  ApiPublicNetlifyStartRoute: ApiPublicNetlifyStartRoute,
  ApiPublicVercelDeployRoute: ApiPublicVercelDeployRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
