/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as ApiPublicVercelDeployRouteImport } from './routes/api/public/vercel.deploy'
import { Route as ApiPublicNetlifyStartRouteImport } from './routes/api/public/netlify.start'
import { Route as ApiPublicNetlifyDeployRouteImport } from './routes/api/public/netlify.deploy'
import { Route as ApiPublicNetlifyCallbackRouteImport } from './routes/api/public/netlify.callback'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVercelDeployRoute = ApiPublicVercelDeployRouteImport.update({
  id: '/api/public/vercel/deploy',
  path: '/api/public/vercel/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNetlifyStartRoute = ApiPublicNetlifyStartRouteImport.update({
  id: '/api/public/netlify/start',
  path: '/api/public/netlify/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNetlifyDeployRoute = ApiPublicNetlifyDeployRouteImport.update({
  id: '/api/public/netlify/deploy',
  path: '/api/public/netlify/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNetlifyCallbackRoute =
  ApiPublicNetlifyCallbackRouteImport.update({
    id: '/api/public/netlify/callback',
    path: '/api/public/netlify/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/builder': typeof BuilderRoute
  '/gallery': typeof GalleryRoute
  '/projects': typeof ProjectsRoute
  '/p/$id': typeof PIdRoute
  '/api/public/netlify/callback': typeof ApiPublicNetlifyCallbackRoute
  '/api/public/netlify/deploy': typeof ApiPublicNetlifyDeployRoute
  '/api/public/netlify/start': typeof ApiPublicNetlifyStartRoute
  '/api/public/vercel/deploy': typeof ApiPublicVercelDeployRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/builder': typeof BuilderRoute
  '/gallery': typeof GalleryRoute
  '/projects': typeof ProjectsRoute
  '/p/$id': typeof PIdRoute
  '/api/public/netlify/callback': typeof ApiPublicNetlifyCallbackRoute
  '/api/public/netlify/deploy': typeof ApiPublicNetlifyDeployRoute
  '/api/public/netlify/start': typeof ApiPublicNetlifyStartRoute
  '/api/public/vercel/deploy': typeof ApiPublicVercelDeployRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/builder': typeof BuilderRoute
  '/gallery': typeof GalleryRoute
  '/projects': typeof ProjectsRoute
  '/p/$id': typeof PIdRoute
  '/api/public/netlify/callback': typeof ApiPublicNetlifyCallbackRoute
  '/api/public/netlify/deploy': typeof ApiPublicNetlifyDeployRoute
  '/api/public/netlify/start': typeof ApiPublicNetlifyStartRoute
  '/api/public/vercel/deploy': typeof ApiPublicVercelDeployRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/builder'
    | '/gallery'
    | '/projects'
    | '/p/$id'
    | '/api/public/netlify/callback'
    | '/api/public/netlify/deploy'
    | '/api/public/netlify/start'
    | '/api/public/vercel/deploy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/builder'
    | '/gallery'
    | '/projects'
    | '/p/$id'
    | '/api/public/netlify/callback'
    | '/api/public/netlify/deploy'
    | '/api/public/netlify/start'
    | '/api/public/vercel/deploy'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/builder'
    | '/gallery'
    | '/projects'
    | '/p/$id'
    | '/api/public/netlify/callback'
    | '/api/public/netlify/deploy'
    | '/api/public/netlify/start'
    | '/api/public/vercel/deploy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  BuilderRoute: typeof BuilderRoute
  GalleryRoute: typeof GalleryRoute
  ProjectsRoute: typeof ProjectsRoute
  PIdRoute: typeof PIdRoute
  ApiPublicNetlifyCallbackRoute: typeof ApiPublicNetlifyCallbackRoute
  ApiPublicNetlifyDeployRoute: typeof ApiPublicNetlifyDeployRoute
  ApiPublicNetlifyStartRoute: typeof ApiPublicNetlifyStartRoute
  ApiPublicVercelDeployRoute: typeof ApiPublicVercelDeployRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vercel/deploy': {
      id: '/api/public/vercel/deploy'
      path: '/api/public/vercel/deploy'
      fullPath: '/api/public/vercel/deploy'
      preLoaderRoute: typeof ApiPublicVercelDeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/netlify/start': {
      id: '/api/public/netlify/start'
      path: '/api/public/netlify/start'
      fullPath: '/api/public/netlify/start'
      preLoaderRoute: typeof ApiPublicNetlifyStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/netlify/deploy': {
      id: '/api/public/netlify/deploy'
      path: '/api/public/netlify/deploy'
      fullPath: '/api/public/netlify/deploy'
      preLoaderRoute: typeof ApiPublicNetlifyDeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/netlify/callback': {
      id: '/api/public/netlify/callback'
      path: '/api/public/netlify/callback'
      fullPath: '/api/public/netlify/callback'
      preLoaderRoute: typeof ApiPublicNetlifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  BuilderRoute: BuilderRoute,
  GalleryRoute: GalleryRoute,
  ProjectsRoute: ProjectsRoute,
  PIdRoute: PIdRoute,
  ApiPublicNetlifyCallbackRoute: ApiPublicNetlifyCallbackRoute,
  ApiPublicNetlifyDeployRoute: ApiPublicNetlifyDeployRoute,
  ApiPublicNetlifyStartRoute: ApiPublicNetlifyStartRoute,
  ApiPublicVercelDeployRoute: ApiPublicVercelDeployRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
